animated card stack animation added
ALPHAVIO/Mirage-UI pull request #162
Opened 2021-07-09 19:19 UTC by Khushi-agarwal

Added the animated card stack animation

## Related issue?
Fixes #102 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [] Have you made the GIF for the component you added?

2021-07-10 06:51 UTC, Pranav016 requested changes
Also update the index with the new component you are adding - https://github.com/ALPHAVIO/Mirage-UI/blob/master/HTML%2BCSS%2BJS/README.md

2021-07-10 06:51 UTC, Pranav016 commented on HTML+CSS+JS/Cards/AnimatedCardStacksAnimation/README.md
> +
You need to add a demo GIF or video for your component, take reference from this-
https://github.com/ALPHAVIO/Mirage-UI/tree/master/React/Navigation-Bar/TopDownAnimation-ResponsiveNavbar

2021-07-10 07:58 UTC, Khushi-agarwal commented
@Pranav016 done the changes.Kindly review them.

2021-07-10 12:55 UTC, theBeginner86 approved these changes
Everything looks good now. 👍

2021-07-10 13:09 UTC, merged

2021-07-11 17:59 UTC, Pranav016 commented
@all-contributors please add @Khushi-agarwal for code

2021-07-11 20:41 UTC, Pranav016 commented
@all-contributors please add @Khushi-agarwal for doc