Issue-159 resolved
ALPHAVIO/Mirage-UI pull request #186
Opened 2021-07-14 20:00 UTC by puneetkaur2929

## What is the change?
Add image overlay effects on hover component

## Related issue?
closes: #159 

## How was it tested?
Remove this line and tell us how the code was tested.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [] Have you made the GIF for the component you added?

## GIF you created:
Add here the GIF you created.

2021-07-14 20:52 UTC, Pranav016 requested changes
- Add a README for you component (use [README template](https://github.com/ALPHAVIO/Mirage-UI/blob/master/README_TEMPLATE.md)) and update the component [index](https://github.com/ALPHAVIO/Mirage-UI/blob/master/HTML%2BCSS%2BJS/README.md) as well

- try writing better commit messages that are descriptive about the code added.

2021-07-16 11:15 UTC, theBeginner86 requested changes
- Actually, there are some minor errors in the syntax.
You need to put enter after each tag you use so that the compiler can understand that you are making use of markdown.

- Rest everything looks good. 👍
Also, the different forms of overlay effect you choose are very reusable.

2021-07-16 11:18 UTC, theBeginner86 requested changes

2021-07-16 11:18 UTC, theBeginner86 commented on HTML+CSS+JS/Image-Animations/ImageOverlayEffects/README.md
> + ## Setup instructions
```suggestion
<div align="center">

![ImageOverlayEffectsvideo -1](https://user-images.githubusercontent.com/80326308/125904828-23e6408e-4c1e-4364-99c1-d0e323e19daf.gif)

![ImageOverlayEffectsvideo-2](https://user-images.githubusercontent.com/80326308/125906642-0dbad981-01ff-405c-89a4-496cdaf90ce5.gif)

![ImageOverlayEffectsvideo-3](https://user-images.githubusercontent.com/80326308/125906118-367756c2-035b-4580-b5b6-5eb76ea5717b.gif)

</div>

 ## Setup instructions
```

2021-07-16 11:18 UTC, theBeginner86 commented on HTML+CSS+JS/Image-Animations/ImageOverlayEffects/README.md
> +# Author
```suggestion
Ready to use.

# Author
```

2021-07-16 11:18 UTC, theBeginner86 commented on HTML+CSS+JS/Image-Animations/ImageOverlayEffects/README.md
> +![Puneet Kaur 😊](https://github.com/puneetkaur2929)
```suggestion
[Puneet Kaur](https://github.com/puneetkaur2929) 
```
#### or

```suggestion
[Puneet Kaur](https://github.com/puneetkaur2929) 😊
```

2021-07-16 16:47 UTC, theBeginner86 approved these changes
LGTM 👍

2021-07-16 16:51 UTC, puneetkaur2929 commented
> LGTM 👍
> 
> > From next time please consider writing better and descriptive commit messages. 🙂

Glad that you liked it.
Ok I ll be careful from next time.

2021-07-16 16:51 UTC, merged