Modal component
ALPHAVIO/Mirage-UI pull request #95
Opened 2021-06-22 07:08 UTC by okarin1511

## What is the change?
Added a Modal component with attributes like header, heading, body, button.

## Related issue?
closes: #70 

## How was it tested?
Tested it on the local development server.

## Checklist:
Before you create this PR, confirm all the requirements listed below by checking the checkboxes `[x]`:

-   [x] Have you followed the [Contribution Guidelines](https://github.com/ALPHAVIO/BlogSite/blob/master/CONTRIBUTING.md) while contributing.
-   [x] Have you checked there aren't other open [Pull Requests](https://github.com/ALPHAVIO/Mirage-UI/pulls) for the same update/change?
-   [x] Have you made corresponding changes to the documentation?
-   [x] Have you tested the code before submission?
-   [x] Did you lint and format your code before making the Pull Request?
-   [x] Have you made the GIF for the component you added?

## GIF you created:
I inserted an image instead.

![image](https://user-images.githubusercontent.com/69676297/122879503-97a8c380-d356-11eb-830d-2287172c3264.png)

2021-06-22 14:46 UTC, Pranav016 requested changes
Pull the recent changes and see how I have added a new react component, follow the same structure. You can take reference on how to cleanup the folder after using create-react-app. Also you can take reference for the README of the component.
- Put your modal component inside a new folder `Modals`
- Cleanup the repo, remove unwanted/ unused images and favicons and files. They bloat the project.
- Add a demo video or GIF, image doesn't help to see functioning of the component.
- Resolve merge conflicts

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/README.md
> +# Getting Started with Create React App
Remove this file

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/public/index.html
> +    -->
Remove unnecessary code and comments

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/public/index.html
> +    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
Remove favicon and logo links from this

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/public/manifest.json
> +{
remove this file

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
remove file

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/src/App.css
> +@keyframes App-logo-spin {
This css is not even used in the actual modal, please check if this is not necessary then remove the file

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/src/App.test.js
> +import { render, screen } from '@testing-library/react';
remove file

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/src/logo.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 841.9 595.3"><g fill="#61DAFB"><path d="M666.3 296.5c0-32.5-40.7-63.3-103.1-82.4 14.4-63.6 8-114.2-20.2-130.4-6.5-3.8-14.1-5.6-22.4-5.6v22.3c4.6 0
remove file

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/src/setupTests.js
> +// jest-dom adds custom jest matchers for asserting on DOM nodes.
remove

2021-06-22 14:46 UTC, Pranav016 commented on React/Modal/modal-component/src/reportWebVitals.js
> +const reportWebVitals = onPerfEntry => {
remove

2021-06-22 14:46 UTC, Pranav016 commented on React/README.md
> +## Modal Component:
This README should be inside the component, it acts as a documentation for the component. You have put it in the wrong place. Also use the README template in the repository to make a README for your component.

2021-06-22 14:46 UTC, Pranav016 commented
Post your video/ GIF here in the comments first before pushing your new changes.

2021-06-23 09:31 UTC, okarin1511 commented
I've made the changes, please review it.

Please let me know if you want me to change anything else

2021-06-23 10:44 UTC, Pranav016 approved these changes

2021-06-23 10:47 UTC, merged